### ISSUE TITLE
Theme file molokai not found

### ISSUE THREAD

**Issue by mikepc** [gregpardo/vim-elixir-ide#2]
Installing colors for first time
Traceback (most recent call last):
  File "./bin/update_colors", line 6, in <module>
    import requests
ImportError: No module named requests
Theme file molokai not found.
Installation failed

**Comment by SophisticaSean** [comment]
so you'll need python3 installed

then do `pip3 install requests`

if you get a `if_lua` error, you need to make sure you have a vim that has lua support, on OSX you can install it with this `brew install vim --with-luajit`

**Comment by SophisticaSean** [comment]
Once I got the setup running autocompletion of elixir AST didn't work.

**Comment by mikepc** [comment]
```

 michael@zor  ~  sh ~/.vim_elixir_runtime/bin/install
Installing colors for first time
Traceback (most recent call last):
  File "./bin/update_colors", line 6, in <module>
    import requests
ImportError: No module named requests
Theme file molokai not found.
Installation failed
 michael@zor  ~  source ~/.bash_profile
 michael@zor  ~  sh ~/.vim_elixir_runtime/bin/install
Installing colors for first time
Traceback (most recent call last):
  File "./bin/update_colors", line 6, in <module>
    import requests
ImportError: No module named requests
Theme file molokai not found.
Installation failed
 michael@zor  ~  pip3 install requests
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests) (1.25.3)
 michael@zor  ~  sh ~/.vim_elixir_runtime/bin/install
Installing colors for first time
Traceback (most recent call last):
  File "./bin/update_colors", line 6, in <module>
    import requests
ImportError: No module named requests
Theme file molokai not found.
Installation failed

```

Bummer.

Found out /usr/bin/env python was still giving me an old version of python.  I manually ran the scripts using python interpreter, and it worked.
